baseURL = "https://minus.usilenie.plus/"
DefaultContentLanguage = "ru"
languageCode = "ru-ru"
title = "Некстджен и Усиление+"
theme = "beautiful"
disqusShortname = "nekstdzhen-i-usilenie"
googleAnalytics = "UA-22075196-6"
enableMissingTranslationPlaceholders = true

[Params]
 subtitle = "Ненавидим видеоигры с 1992 года, теперь в журнальном формате"
 logo = "img/logo.png"
 favicon = "img/favicon.png"
 rss = true
 comments = true
 showRelatedPosts = true
 featuredImagesOnFrontpage = false

[Author]
 name = "Юрий Крупенин"
 twitter = "turbojedi"
 instagram = "turbojedi"
 github = "yurikrupenin"
 twitch = "cubeofwood"
 goodreads = "5512374-yuri-krupenin"
 strava = "5870047"


[[menu.main]]
 name = "Видеоигры"
 url = "categories/видеоигры"
 weight = 1 

[[menu.main]]
 name = "Велосипеды"
 url = "categories/велосипеды"
 weight = 5 

[[menu.main]]
 identifier = "other"
 name = "Другое"
 weight = 10 

[[menu.main]]
 parent = "other"
 name = "Технологии"
 url = "categories/технологии"

[[menu.main]]
 parent = "other"
 name = "Туризм"
 url = "categories/туризм"

[[menu.main]]
 parent = "other"
 name = "Шитпостинг"
 url = "categories/шитпостинг"
