baseURL = "https://usilenie.plus/"
DefaultContentLanguage = "ru"
languageCode = "ru-ru"
title = "Некстджен и Усиление+"
theme = "beautiful"
googleAnalytics = "UA-22075196-6"
enableMissingTranslationPlaceholders = false
timeout = 3600000

[markup]
defaultMarkdownHandler = "blackfriday"

[blackfriday]
angledQuotes = true
hrefTargetBlank = true

[Params]
 subtitle = "Больно читать? В этом вся задумка."
 logo = "img/logo_2.png"
 favicon = "img/favicon.png"
 rss = true
 showRelatedPosts = true
 featuredImagesOnFrontpage = false

[Author]
 name = "Юрий Крупенин"
 twitter = "turbojedi"
 telegram = "usilenie_plus"
 instagram = "turbojedi"
 github = "yurikrupenin"
 twitch = "cubeofwood"
 goodreads = "5512374-yuri-krupenin"
 strava = "5870047"

 [imaging]
 resampleFilter = "lanczos"
 anchor = "smart"
 quality = 95


[[menu.main]]
 name = "Видеоигры"
 url = "categories/видеоигры"
 weight = 1

[[menu.main]]
 name = "Велосипеды"
 url = "categories/велосипеды"
 weight = 5

[[menu.main]]
 identifier = "other"
 name = "Другое"
 weight = 10

[[menu.main]]
 parent = "other"
 name = "Технологии"
 url = "categories/технологии"
 weight = 1

[[menu.main]]
 parent = "other"
 name = "Туризм"
 url = "categories/туризм"
 weight = 3

[[menu.main]]
 parent = "other"
 name = "Шитпостинг"
 url = "categories/шитпостинг"
 weight = 5

 [[menu.main]]
 parent = "other"
 name = "Все категории"
 url = "categories"
 weight = 10
